added new features

diff --git a/defos b/defos
--- a/defos
+++ b/defos
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-#       .___      _____             
+#       .___      _____
 #     __| _/_____/ ____\____  ______   Nehar Tale DeFc0n
 #    / __ |/ __ \   __\/  _ \/  ___/  https://www.github.com/xDeFc0nx/
-#   / /_/ \  ___/|  | (  <_> )___ \ 
+#   / /_/ \  ___/|  | (  <_> )___ \
 #   \____ |\___  >__|  \____/____  >
-#        \/    \/                \/ 
+#        \/    \/                \/
 # NAME: DEFOS
 # DESC: An installation and deployment script for DeFc0n's Xmonad desktop.
 # WARNING: Run this script at your own risk.
@@ -21,8 +21,10 @@ if [ "$(id -u)" = 0 ]; then
     exit 1
 fi
 
-error() { \
-    clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
+error() {
+    clear
+    printf "ERROR:\\n%s\\n" "$1" >&2
+    exit 1
 }
 
 echo "################################################################"
@@ -30,7 +32,7 @@ echo "## Syncing the repos and installing 'dialog' if not installed ##"
 echo "################################################################"
 sudo pacman --noconfirm --needed -Syu dialog || error "Error syncing the repos."
 
-welcome() { \
+welcome() {
     dialog --colors --title "\Z7\ZbInstalling DEFOS!" --msgbox "\Z4This is a script that will install what I sarcastically call DEFOS (DeFc0n's operating system).  It's really just an installation script for those that want to try out my XMonad desktop.  We will add DEFOS repos to Pacman and install the XMonad tiling window manager, the Xmobar panel, the Alacritty terminal, the Fish shell, Doom Emacs and many other essential programs needed to make my dotfiles work correctly.\\n\\n-DeFc0n (Nehar tale,)" 16 60
 
     dialog --colors --title "\Z7\ZbStay near your computer!" --yes-label "Continue" --no-label "Exit" --yesno "\Z4This script is not allowed to be run as root, but you will be asked to enter your sudo password at various points during this installation. This is to give PACMAN the necessary permissions to install the software.  So stay near the computer." 8 60
@@ -38,13 +40,16 @@ welcome() { \
 
 welcome || error "User choose to exit."
 
-lastchance() { \
-    dialog --colors --title "\Z7\ZbInstalling DTOS!" --msgbox "\Z4WARNING! The DTOS installation script is currently in public beta testing. There are almost certainly errors in it; therefore, it is strongly recommended that you not install this on production machines. It is recommended that you try this out in either a virtual machine or on a test machine." 16 60
+lastchance() {
+    dialog --colors --title "\Z7\ZbInstalling DEFOS!" --msgbox "\Z4WARNING! The DEFOS installation script is currently in public beta testing. There are almost certainly errors in it; therefore, it is strongly recommended that you not install this on production machines. It is recommended that you try this out in either a virtual machine or on a test machine." 16 60
 
-    dialog --colors --title "\Z7\ZbAre You Sure You Want To Do This?" --yes-label "Begin Installation" --no-label "Exit" --yesno "\Z4Shall we begin installing DTOS?" 8 60 || { clear; exit 1; }
+    dialog --colors --title "\Z7\ZbAre You Sure You Want To Do This?" --yes-label "Begin Installation" --no-label "Exit" --yesno "\Z4Shall we begin installing DEFOS?" 8 60 || {
+        clear
+        exit 1
+    }
 }
 # Let's install each package listed in the pkglist.txt file.
-sudo pacman --needed --ask 4 -Sy - < pkglist.txt
+sudo pacman --needed --ask 4 -Sy - <pkglist.txt
 yay -S tlauncher google-chrome betterdiscordctl --noconfirm
 
 cd ~
@@ -54,7 +59,9 @@ yes | cp -r .bashrc $HOME
 yes | cp -r .zshrc $HOME
 yes | cp -r .xmonad $HOME
 yes | cp -r .config $HOME
-xmonad_recompile() { \
+yes | cp -r scripts $HOME
+yes | cp -r wallpapers $HOME
+xmonad_recompile() {
     echo "########################"
     echo "## Recompiling XMonad ##"
     echo "########################"
@@ -63,7 +70,7 @@ xmonad_recompile() { \
 
 xmonad_recompile || error "Error recompiling Xmonad!"
 
-xmonadctl_compile() { \
+xmonadctl_compile() {
     echo "####################################"
     echo "## Compiling the xmonadctl script ##"
     echo "####################################"
@@ -76,23 +83,23 @@ PS3='Set default user shell (enter number): '
 shells=("fish" "bash" "zsh" "quit")
 select choice in "${shells[@]}"; do
     case $choice in
-         fish | bash | zsh)
-            sudo chsh $USER -s "/bin/$choice" && \
+    fish | bash | zsh)
+        sudo chsh $USER -s "/bin/$choice" &&
             echo -e "$choice has been set as your default USER shell. \
                     \nLogging out is required for this take effect."
-            break
-            ;;
-         quit)
-            echo "User quit without changing shell."
-            break
-            ;;
-         *)
-            echo "invalid option $REPLY"
-            ;;
+        break
+        ;;
+    quit)
+        echo "User quit without changing shell."
+        break
+        ;;
+    *)
+        echo "invalid option $REPLY"
+        ;;
     esac
 done
 
-# Disable the current login manager
+# # Disable the current login manager
 sudo systemctl disable $(grep '/usr/s\?bin' /etc/systemd/system/display-manager.service | awk -F / '{print $NF}') || echo "Cannot disable current display manager."
 # Enable sddm as login manager
 sudo systemctl enable sddm
@@ -101,26 +108,25 @@ echo "## Enable sddm as login manager. ##"
 echo "###################################"
 
 ## Make multicolor-sddm-theme the default sddm theme ##
-# This is the sddm system configuration file.
-[ -f "/usr/lib/sddm/sddm.conf.d/default.conf" ] && \
-    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /usr/lib/sddm/sddm.conf.d/default.conf.backup && \
+#  #This is the sddm system configuration file.
+[ -f "/usr/lib/sddm/sddm.conf.d/default.conf" ] &&
+    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /usr/lib/sddm/sddm.conf.d/default.conf.backup &&
     sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /usr/lib/sddm/sddm.conf.d/default.conf
 
 # This is the sddm local configuration file.
-[ -f "/etc/sddm.conf" ] && \
-    sudo cp /etc/sddm.conf /etc/sddm.conf.backup && \
+[ -f "/etc/sddm.conf" ] &&
+    sudo cp /etc/sddm.conf /etc/sddm.conf.backup &&
     sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /etc/sddm.conf
 
-# Create a local configuration file if it doesn't exist.
-# Standard Arch Linux does not create this file by default.
-[ ! -f "/etc/sddm.conf" ] && \
-    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf || echo "Default sddm system config file is not found."
+# # Create a local configuration file if it doesn't exist.
+# # Standard Arch Linux does not create this file by default.
+# [ ! -f "/etc/sddm.conf" ] && \
+#     sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf || echo "Default sddm system config file is not found."
 
-# ArcoLinux B Awesome uses this config location.
-[ -f "/etc/sddm.conf.d/kde_settings.conf" ] && \
-    sudo cp /etc/sddm.conf.d/kde_settings.conf /etc/sddm.conf.d/kde_settings.backup && \
-    sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /etc/sddm.conf.d/kde_settings.conf
-
+# # ArcoLinux B Awesome uses this config location.
+# [ -f "/etc/sddm.conf.d/kde_settings.conf" ] && \
+#     sudo cp /etc/sddm.conf.d/kde_settings.conf /etc/sddm.conf.d/kde_settings.backup && \
+#     sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /etc/sddm.conf.d/kde_settings.conf
 
 # Enable virt manager
 echo "###################################"
@@ -130,8 +136,6 @@ sudo systemctl enable libvirtd.service
 sudo systemctl start libvirtd.service
 sudo usermod -a -G libvirt $USER
 
-
-
 echo "##############################"
 echo "## DEFOS has been installed! ##"
 echo "##############################"
@@ -139,9 +143,9 @@ echo "##############################"
 while true; do
     read -p "Do you want to reboot to get your DeFoS? [Y/n] " yn
     case $yn in
-        [Yy]* ) reboot;;
-        [Nn]* ) break;;
-        "" ) reboot;;
-        * ) echo "Please answer yes or no.";;
+    [Yy]*) reboot ;;
+    [Nn]*) break ;;
+    "") reboot ;;
+    *) echo "Please answer yes or no." ;;
     esac
 done
